FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl wget gnupg default-libmysqlclient-dev build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY requirements-dev.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
