FROM apache/airflow:3.0.6-python3.11

USER root
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

USER airflow
WORKDIR /opt/airflow

COPY requirements-airflow.txt .
RUN pip install --no-cache-dir -r requirements-airflow.txt
