FROM python:3.11-slim

WORKDIR /app

COPY requirements-crawler.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./crawler /app/crawler

CMD ["python", "-m", "crawler.main"]
