FROM python:3.11-slim

WORKDIR /app

COPY requirements-producer.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./producer /app/producer

CMD ["python", "-m", "producer.main"]
