FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    build-essential \
    libpq-dev \
 && rm -rf /var/lib/apt/lists/*

COPY requirements-no-airflow.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./consumers /app/consumers
COPY ./db /app/db
COPY ./medallion_architect /app/medallion_architect
COPY ./configs /app/configs

ENV PYTHONPATH=/app:$PYTHONPATH

CMD ["python", "-m", "consumers.news_consumers"]
